### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by lolbit1878** [karanlvm/Pong#1]
how do you change the ball speed it goes too fast

**Comment by karanlvm** [comment]
Please check lines 36-43 for ball settings. 

Line 37 **does not** represent the speed at which the ball moves in-game but rather how fast it is drawn on the screen. 

To change the ball speed in the game, you need to go to line 42 and 43 which basically tells you how many pixels the ball moves each time, and alter that to a lower number. 

For example, 

Try changing 
```
ball.dx = 0.25
ball.dy = -0.25

```
to 

```
ball.dx = 0.025
ball.dy = -0.025
```
